export const Roles: string[] = [
  "AI Engineer",
  "Algorithm Engineer",
  "Android Developer",
  "AR/VR Developer",
  "Automation Engineer",
  "Backend Developer",
  "Big Data Engineer",
  "Blockchain Developer",
  "Business Intelligence Analyst",
  "Cloud Architect",
  "Cloud Engineer",
  "Computer Vision Engineer",
  "Cybersecurity Analyst",
  "Cybersecurity Engineer",
  "Data Analyst",
  "Data Architect",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Digital Marketing Analyst",
  "Digital Transformation Consultant",
  "Distributed Systems Engineer",
  "Embedded Systems Engineer",
  "Ethical Hacker",
  "Firmware Engineer",
  "Frontend Developer",
  "Full Stack Developer",
  "Game Developer",
  "Game Designer",
  "Hardware Design Engineer",
  "Hardware Engineer",
  "iOS Developer",
  "IT Consultant",
  "IT Support Specialist",
  "Machine Learning Engineer",
  "Machine Learning Researcher",
  "Mobile App Developer",
  "Natural Language Processing (NLP) Engineer",
  "Network Administrator",
  "Network Engineer",
  "Penetration Tester",
  "Platform Engineer",
  "Product Designer",
  "Product Manager",
  "Program Manager",
  "QA Engineer",
  "Quality Assurance Analyst",
  "Robotics Engineer",
  "Site Reliability Engineer (SRE)",
  "Software Architect",
  "Software Consultant",
  "Software Developer",
  "Software Engineer",
  "Solutions Architect",
  "Support Engineer",
  "Systems Administrator",
  "Systems Analyst",
  "Technical Program Manager",
  "Technical Project Manager",
  "Technical Support Specialist",
  "Technical Writer",
  "Test Automation Engineer",
  "UI Designer",
  "UI/UX Designer",
  "UX Researcher",
  "Video Game Tester",
  "Virtualization Engineer",
  "Web Developer",
  "Webmaster",
];

export const Stacks: string[] = [
  "AJAX",
  "Angular",
  "Apache",
  "ASP.NET",
  "AWS (Amazon Web Services)",
  "Backbone.js",
  "Bash",
  "Bootstrap",
  "C",
  "C#",
  "C++",
  "Cassandra",
  "CircleCI",
  "Cloudflare",
  "CockroachDB",
  "CSS",
  "D3.js",
  "Deno",
  "Django",
  "Docker",
  "Drupal",
  "Elastic Stack (ELK)",
  "Elasticsearch",
  "Electron",
  "Ember.js",
  "Express.js",
  "Figma",
  "Firebase",
  "Flask",
  "Flutter",
  "Gatsby.js",
  "Git",
  "GitHub",
  "GitLab",
  "Go (Golang)",
  "Google Cloud Platform (GCP)",
  "GraphQL",
  "Groovy",
  "Grunt",
  "Gulp",
  "Hadoop",
  "Haskell",
  "HTML",
  "Ionic",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Jira",
  "jQuery",
  "JSON",
  "Kafka",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Linux",
  "MariaDB",
  "Memcached",
  "MongoDB",
  "Mongoose",
  "MySQL",
  "NestJS",
  "Next.js",
  "NGINX",
  "Node.js",
  "Nuxt.js",
  "Objective-C",
  "OpenShift",
  "Perl",
  "PHP",
  "PostgreSQL",
  "Puppeteer",
  "Python",
  "RabbitMQ",
  "Rails (Ruby on Rails)",
  "Raspberry Pi",
  "React",
  "Redis",
  "Redux",
  "REST APIs",
  "Ruby",
  "Rust",
  "SASS",
  "Scala",
  "Selenium",
  "Shell Scripting",
  "Spring Boot",
  "SQLite",
  "Svelte",
  "Swift",
  "Symfony",
  "Tailwind CSS",
  "Terraform",
  "TypeScript",
  "Ubuntu",
  "Unity",
  "Unreal Engine",
  "Vue.js",
  "Webpack",
  "WordPress",
  "Xamarin",
  "XML",
  "YAML",
  "Zabbix",
  "Zend Framework",
];


type Contributor = {
  username: string;
  email: string;
  role: string;
  image?: string;
}

export const Contributors: Contributor[] = [
  {
    username: "@coderharry",
    email: "user1@GoMail.com",
    role: "Front-end developer"
  },
  {
    username: "@julianadesigns",
    email: "user2@GoMail.com",
    role: "Product designer"
  },
  {
    username: "@lilythedesigner",
    email: "user3@GoMail.com",
    role: "Product designer"
  },
  {
    username: "@rickmolley",
    email: "user4@GoMail.com",
    role: "Back-end developer"
  },
  {
    username: "@username",
    email: "user5@GoMail.com",
    role: "Back-end developer"
  },
]